Montgardin : ajout photos sur site
planeur-net/outlanding pull request #127
Opened 2024-02-21 10:29 UTC by delta217

Mieux vaut ne pas toucher avant la buse : "bumpy" dit le guide...

2024-02-26 14:42 UTC, llauner requested changes

2024-02-26 14:42 UTC, llauner commented on Pics/318_Montgardin_2.jpg
Buse = le drain ?

2024-02-26 14:42 UTC, llauner commented on Pics/318_Montgardin_1.jpg
Est ce que la taille du fichier peut etre diminue si tu sauvegarde en jpg 70% de qualite ?

2024-02-26 14:42 UTC, llauner commented on Pics/318_Montgardin_2.jpg
Est ce que la taille du jpg peut etre diminuee en jpg 70% ?

2024-02-26 14:42 UTC, llauner commented on Pics/318_Montgardin_1.jpg
Tu peux ajouter la rosace indiquant le N (elle est sur le repo).
Sinon je le fais..

2024-02-26 14:42 UTC, llauner commented on Pics/318_Montgardin_2.jpg
Rosace indiquant le N ? (sinon je le fais)

2024-02-26 14:42 UTC, llauner commented on Pics/318_Montgardin_3.jpg
Je pense qu'il faudrait mettre le drain dans un "rectangle" orange pour indiquer le danger.

2024-02-26 14:42 UTC, llauner commented on Pics/318_Montgardin_2.jpg
Coherence des commentaires dans photo: il faudrait qu'ils utilisent tous la meme chose = voir les autres photos, ou alors au moins faire une coherence sur le meme champs (couleur de fond du rectangle, taille police, ..)

2024-02-26 16:29 UTC, delta217 commented on Pics/318_Montgardin_2.jpg
Le blème, c'est que j'ai fait çà dans deux logiciels différents, sur le téléphone et sur le PC. Donc, il me faut reprendre le tout.
A part çà, j'en ai un autre, excellent pour le coup (en fonction des cultures...), 2km à l'Est.

2024-02-26 16:30 UTC, delta217 commented on Pics/318_Montgardin_1.jpg
J'ai déjà fait, mais peut remettre une louche...

2024-02-26 16:30 UTC, delta217 commented on Pics/318_Montgardin_3.jpg
C'est plus le terrain avant qui est "bumpy" que la buse elle-même. Le gars qui touche 5 m avant la buse a pas mal de chance de redécoller en la passant... Mais on peut colorer.

2024-02-29 11:08 UTC, llauner commented on Pics/318_Montgardin_1.jpg
La photo 1 et 2 font double usage.
Est ce que tu peux m'envoyer les photos sans les annotation ? je vais ajouter les annotations avec le meme style et reduire la taille.

2024-03-03 15:44 UTC, delta217 commented on Pics/318_Montgardin_1.jpg
![318_montgardin_1](https://github.com/planeur-net/outlanding/assets/154979750/c70df29d-c62c-45b5-98cc-c278c310669f)
![318_montgardin_2](https://github.com/planeur-net/outlanding/assets/154979750/34204fb1-e288-4c20-aa08-478726ca9f9c)
![318_montgardin_3](https://github.com/planeur-net/outlanding/assets/154979750/0b46150c-58f8-48f0-a42a-a2cb3ff7cca2)
voili-voilà...!

2024-03-05 07:51 UTC, llauner commented
Ok pour toi comme ca ?

2024-03-05 08:43 UTC, delta217 commented
OK, tu veux que je te montre le "beau champs" qui est à ékm de là ?
Et que, perso, je prendrais plus volontiers s'il était en état !

2024-03-05 09:42 UTC, merged