Alpes du Nord : 5 champs de Habère-Poche + LF7470 Cervens
planeur-net/outlanding pull request #22
Opened 2024-01-02 15:25 UTC by delta217

Merci aux copains d'Habère Poche !

2024-01-02 19:20 UTC, llauner requested changes

2024-01-02 19:20 UTC, llauner commented on champs_des_alpes.cup
> +"Thône CV",Thone,FR,4553.667N,00620.385E,653.0m,3,231,260.0m,30.0m,,"tres bien - preferer QFU SW",,"thone.jpg"
Eviter les accents, souvent ca s'affiche mal.
Ca veut dire quoi CV ? Champs Vachable ? a enlever on sait que c'est un champs
Ca veut dire quoi tres bien ? facile ?
Coherence des commentaires:
Preferer QFU SW

2024-01-02 19:31 UTC, delta217 commented on Pics_champs_des_alpes/LF7470.jpg
J'avais mis ces icônes sur ma carte pour aller les visiter à pied... mais je peux les retirer (sauf pour Cervens)

2024-01-02 19:35 UTC, delta217 commented on champs_des_alpes.cup
> +"Thône CV",Thone,FR,4553.667N,00620.385E,653.0m,3,231,260.0m,30.0m,,"tres bien - preferer QFU SW",,"thone.jpg"
Oui Champ Vachable, appellation Habère-Poche aussi...

2024-01-02 19:38 UTC, delta217 commented on champs_des_alpes.cup
> +"Alex",Alex,FR,4553.250N,00613.100E,570.0m,3,197,300.0m,30.0m,,"monte 4% vers le Sud - Choisir en fonction des cultures - Attention chemin entre les 2 champs.",,"alex.jpg"
Tu veux que je vire les tirets du 6, c'est çà ?

2024-01-02 19:39 UTC, delta217 commented
En pratique, je refais une branche, je la merge sur mon main, et je renouvelle la PR ?

2024-01-02 19:48 UTC, delta217 commented on champs_des_alpes.cup
> +"Cervens",LF7470,FR,4617.583N,00626.800E,610.0m,2,54,310.0m,,"123.5","123.5",,"LF7470.jpg"
Et non, la direction est en degrés dans le format .cup : donc 60 si on veut une "06"... même problème que pour Lesche.
Je pense que l'interdiction du dimanche ne vaut que pour les motorisés !?
Et je ne peux pas mettre de virgule dans le texte.

2024-01-02 20:48 UTC, llauner commented on Pics_champs_des_alpes/LF7470.jpg
On peut le laisser pour Cervens si tu veux.

2024-01-02 20:52 UTC, llauner commented on champs_des_alpes.cup
> +"Cervens",LF7470,FR,4617.583N,00626.800E,610.0m,2,54,310.0m,,"123.5","123.5",,"LF7470.jpg"
OK. Effectivement c'est en degres. Ca veut dire qu'il faut que je verifie le fichier de guide des aires...je dois avoir des QFU plutot que des degres...Mettons des degres c'est plus "rapide" a comprendre. Donc 60

2024-01-02 20:53 UTC, llauner commented on champs_des_alpes.cup
> +"Alex",Alex,FR,4553.250N,00613.100E,570.0m,3,197,300.0m,30.0m,,"monte 4% vers le Sud - Choisir en fonction des cultures - Attention chemin entre les 2 champs.",,"alex.jpg"
Oui c'est ca.
Le format des commentaires c'est: Blala bla. Reblabla

2024-01-02 20:53 UTC, llauner commented on champs_des_alpes.cup
> +"Thône CV",Thone,FR,4553.667N,00620.385E,653.0m,3,231,260.0m,30.0m,,"tres bien - preferer QFU SW",,"thone.jpg"
On degage le CV, on voit que c'est un champs vachable dans le type

2024-01-02 20:55 UTC, llauner commented
Non, ne surtout pas refaire de branche !
Tu corriges justement dans la meme branche, et ca fait des nouveaux commits qui corrigent. C'est l'idee.
Du coups on voit apparaitre les correction dans la meme PR: c'est ca l'interet de la PR, tu fais un commentaire, l'autre fait la correction, et apres tu vois la correction...

2024-01-02 21:10 UTC, delta217 commented
Trop tard... J'avais mergé Chablais sur mon main, fait le PR depuis mon main, puis deleté Chablais aussi sec !
Donc, je suis sur un Chablais2 (pas Chablis..., enfin, pas encore !).

2024-01-03 16:55 UTC, delta217 commented
Et donc, j'ai mergé mon Chablais2 avec mon main, de peur que mon main soit en conflit avec le main principal.
Bonne idée, je ne sais pas...

2024-01-03 17:28 UTC, merged