La palud - correction longueur et QFU, photo 2
planeur-net/outlanding pull request #89
Opened 2024-01-18 18:14 UTC by delta217

2024-01-18 20:09 UTC, llauner requested changes

2024-01-18 20:09 UTC, llauner commented on Pics/229_la_ palud_2.jpg
Tu peux faire la capture sans le truc gris en bas a droite ?
![image](https://github.com/planeur-net/outlanding/assets/32835597/b31ec0fc-461d-4729-81e6-98c9571241a4)

Est ce que tu peux sauvegarder le jpg avec 70% de qualite pour que la taille ne soit pas aussi importante ? (la c'est 212KB)

2024-01-18 20:09 UTC, llauner commented on guide_aires_securite.cup
> +"229 Palud Verdon",229,FR,4346.783N,00621.183E,890.0m,3,135,240.0m,,,"100/280 Reco a pied recommandee. Prairie. {difficile}",,"229_La_palud_sur_Verdon.jpg;229_la_palud_2.jpg"
OK j'ajouterai les deviations par rapport au guide avant le merge de la PR...

2024-01-19 09:15 UTC, delta217 commented on Pics/229_la_ palud_2.jpg
c'est le curseur du zoom. Faut que je regarde si je peux le virer ?

2024-01-19 09:23 UTC, llauner commented on Pics/229_la_ palud_2.jpg
> c'est le curseur du zoom. Faut que je regarde si je peux le virer ?

Oui.
Ce que je fais c'est que je fais "Print map" et apres "patage" et je sauvegarde vers Google Drive
En faisant "Print map" il n'y a pas ca sur la photo...

2024-01-19 09:54 UTC, delta217 commented on Pics/229_la_ palud_2.jpg
done...

2024-01-19 10:06 UTC, merged