#96 Nettoyage et demenagement de cols
planeur-net/outlanding pull request #97
Opened 2024-01-21 10:31 UTC by llauner

2024-01-21 17:20 UTC, delta217 requested changes
Vous avez bien travaillé, chef..., vous méritez vos plumes ! 
J'ai passé en revue tous les cols !

- col Corgella : c'est celui que j'avais supprimé, je pense que c'est le pizzo di Corgella qui s'est retrouvé par erreur dans les cols.
- col de Roselend s'appelle Cormet de Roselend
- col du Caduc est en fait le col du Mourre Gros
- col des Rochilles ; positionnement
- col des Touretttes : idem
- col du grd st Bernard : idem
- col vert : idem
- col du Tour : parfait !!!

2024-01-22 07:20 UTC, llauner commented
Ok je vais corriger ...
Et pour la localisation elle était bonne sur ton fichier où il faut que je la retrouve ?

2024-01-22 08:31 UTC, delta217 commented
En principe, c'est bon sur mon fichier,.. sauf si je m'a planté !

2024-01-22 11:40 UTC, llauner commented
> En principe, c'est bon sur mon fichier,.. sauf si je m'a planté !

OK ca marche. Je regarde ca sans doute demain...

2024-01-23 07:12 UTC, llauner commented
C'est corrige..

2024-01-23 13:45 UTC, delta217 approved these changes

2024-01-23 13:46 UTC, merged