col de Grimone
planeur-net/outlanding pull request #98
Opened 2024-01-23 20:27 UTC by delta217

2024-01-24 06:53 UTC, llauner requested changes

2024-01-24 06:53 UTC, llauner commented on cols_des_alpes.cup
> +"Col de Grimone",C-Grmone,FR,4441.500N,00539.250E,1319.0m,6,,,,,"{col},,
Il manque un " pour fermer les commentaires apres {col}

2024-01-25 07:13 UTC, llauner commented
Tu dois etre absent..je vais faire la petite modif et merger..

2024-01-25 07:15 UTC, merged

2024-01-25 08:53 UTC, delta217 commented
C'était RTT hier..., je suis allé reconnaitre la face Nord des aiguilles de Chabrières, et jeter un oeil sur le Guillaume et la tête d'Esclicis...

![20240124_10](https://github.com/planeur-net/outlanding/assets/154979750/162e0460-2545-43ae-8c16-1875b638e781)


![20240124_116](https://github.com/planeur-net/outlanding/assets/154979750/d75aa550-6f87-4e49-a963-03102f16896c)